name: GitHub Profile 3D Contrib

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza todo dia à meia-noite UTC
  workflow_dispatch:     # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    steps:
      - uses: yoshi389111/github-profile-3d-contrib@master
        with:
          token: ${{ secrets.GH_TOKEN }}
